using System;
using UnityEngine;

[Serializable]
public abstract class BaseControls {
	/// <summary>
	/// Called when this control is enabled.
	/// </summary>
	public virtual void OnEnable() { return; }

	/// <summary>
	/// Gets the movement vector of the player.
	/// </summary>
	/// <returns>The new movement vector</returns>
	/// <param name="current">the current movement vector</param>
    public abstract Vector3 GetMove(Vector3 current);

	/// <summary>
	/// Gets the relative rotation of the player.
	/// </summary>
	/// <returns>The rotation generated by either the gyroscope or the compass.</returns>
	/// <param name="current">The current rotation o tha player</param>
    public abstract Quaternion GetRotation(Quaternion current);

	/// <summary>
	/// Called when this control is disabled.
	/// When using touch controls, this disables the gyro/compass
	/// </summary>
	public virtual void OnDisable() { return; }

	/// <summary>
	/// Gets the type of the control.
	/// </summary>
	/// <returns>The type of the control</returns>
	public abstract ControllerOption GetType();
}

public enum ControllerOption {
	SingleAxisControls, FixedDirectionControls, MobileControls, FirstPersonShooterControls, OculusRiftControls
}

